export const SOCKET_EVENTS = {
  CREATE_GAME: 'CREATE_GAME',
  AFTER_GAME_CREATED: 'AFTER_GAME_CREATED',
  PLAYER_JOIN: 'PLAYER_JOIN',
  NOTIFY_PLAYER_JOIN: 'NOTIFY_PLAYER_JOIN',
  START_GAME: 'START_GAME',
  STARTED_GAME: 'STARTED_GAME',
  TURN_UPDATE: 'TURN_UPDATE',
  TABLE_ROUND: 'TABLE_ROUND',
  ADD_CARD_TABLE: 'ADD_CARD_TABLE',
  CLEAR_TABLE: 'CLEAR_TABLE'
}